version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./environment/dev/Dockerfile
    image: dev/panic-fab-signaling-server
    container_name: panic-fab-signaling-server
    volumes:
      - ../..:/code
    ports:
      - "3000:3000"
      - "9229:9229"